/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

/**
 *
 * @author Juan
 */
public class NuevoProveedorScreen extends javax.swing.JFrame {

    /**
     * Creates new form NuevoProveedorScreen
     */
    public NuevoProveedorScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informacionProveedorPanel = new javax.swing.JPanel();
        razonSocialLabel = new javax.swing.JLabel();
        cuitLabel = new javax.swing.JLabel();
        domicilioLabel = new javax.swing.JLabel();
        sitioWebLabel = new javax.swing.JLabel();
        direccionEmailLabel = new javax.swing.JLabel();
        razonSocialTextField = new javax.swing.JTextField();
        cuitTextField = new javax.swing.JTextField();
        domicilioTextField = new javax.swing.JTextField();
        sitioWebTextField = new javax.swing.JTextField();
        direccionEmailTextField = new javax.swing.JTextField();
        campoObligatorioRazonSocialLabel = new javax.swing.JLabel();
        campoObligatorioCuitLabel = new javax.swing.JLabel();
        campoObligatorioDomicilioLabel = new javax.swing.JLabel();
        referenciaCamposObligatorios = new javax.swing.JLabel();
        cancelarButton = new javax.swing.JButton();
        aceptarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo Proveedor");
        setResizable(false);

        informacionProveedorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese la informacion del nuevo proveedor:"));

        razonSocialLabel.setText("Razon Social:");

        cuitLabel.setText("CUIT:");

        domicilioLabel.setText("Domicilio:");

        sitioWebLabel.setText("Sitio Web:");

        direccionEmailLabel.setText("Direccion de E-mail:");

        razonSocialTextField.setPreferredSize(new java.awt.Dimension(175, 20));

        campoObligatorioRazonSocialLabel.setForeground(new java.awt.Color(255, 0, 0));
        campoObligatorioRazonSocialLabel.setText("*");

        campoObligatorioCuitLabel.setForeground(new java.awt.Color(255, 0, 0));
        campoObligatorioCuitLabel.setText("*");

        campoObligatorioDomicilioLabel.setForeground(new java.awt.Color(255, 0, 0));
        campoObligatorioDomicilioLabel.setText("*");

        referenciaCamposObligatorios.setForeground(new java.awt.Color(255, 0, 0));
        referenciaCamposObligatorios.setText("* Campos Obligatorios");

        javax.swing.GroupLayout informacionProveedorPanelLayout = new javax.swing.GroupLayout(informacionProveedorPanel);
        informacionProveedorPanel.setLayout(informacionProveedorPanelLayout);
        informacionProveedorPanelLayout.setHorizontalGroup(
            informacionProveedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionProveedorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacionProveedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informacionProveedorPanelLayout.createSequentialGroup()
                        .addGroup(informacionProveedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(razonSocialLabel)
                            .addComponent(cuitLabel)
                            .addComponent(domicilioLabel)
                            .addComponent(sitioWebLabel)
                            .addComponent(direccionEmailLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(informacionProveedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(direccionEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sitioWebTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(informacionProveedorPanelLayout.createSequentialGroup()
                                .addComponent(domicilioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoObligatorioDomicilioLabel))
                            .addGroup(informacionProveedorPanelLayout.createSequentialGroup()
                                .addComponent(cuitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoObligatorioCuitLabel))
                            .addGroup(informacionProveedorPanelLayout.createSequentialGroup()
                                .addComponent(razonSocialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoObligatorioRazonSocialLabel))))
                    .addComponent(referenciaCamposObligatorios))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        informacionProveedorPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cuitTextField, direccionEmailTextField, domicilioTextField, razonSocialTextField, sitioWebTextField});

        informacionProveedorPanelLayout.setVerticalGroup(
            informacionProveedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionProveedorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacionProveedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(razonSocialLabel)
                    .addComponent(razonSocialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoObligatorioRazonSocialLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacionProveedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuitLabel)
                    .addComponent(cuitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoObligatorioCuitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacionProveedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(domicilioLabel)
                    .addComponent(domicilioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoObligatorioDomicilioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacionProveedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sitioWebLabel)
                    .addComponent(sitioWebTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacionProveedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionEmailLabel)
                    .addComponent(direccionEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(referenciaCamposObligatorios))
        );

        cancelarButton.setText("Cancelar");

        aceptarButton.setText("Aceptar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(informacionProveedorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(aceptarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(informacionProveedorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton)
                    .addComponent(aceptarButton))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(364, 282));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoProveedorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoProveedorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoProveedorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoProveedorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoProveedorScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JLabel campoObligatorioCuitLabel;
    private javax.swing.JLabel campoObligatorioDomicilioLabel;
    private javax.swing.JLabel campoObligatorioRazonSocialLabel;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel cuitLabel;
    private javax.swing.JTextField cuitTextField;
    private javax.swing.JLabel direccionEmailLabel;
    private javax.swing.JTextField direccionEmailTextField;
    private javax.swing.JLabel domicilioLabel;
    private javax.swing.JTextField domicilioTextField;
    private javax.swing.JPanel informacionProveedorPanel;
    private javax.swing.JLabel razonSocialLabel;
    private javax.swing.JTextField razonSocialTextField;
    private javax.swing.JLabel referenciaCamposObligatorios;
    private javax.swing.JLabel sitioWebLabel;
    private javax.swing.JTextField sitioWebTextField;
    // End of variables declaration//GEN-END:variables
}
