/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class NuevoLoteScreen extends javax.swing.JFrame {
    
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;    

    /**
     * Creates new form NuevoLoteScreen
     */
    public NuevoLoteScreen() {
        initComponents();
        try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", "root");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error en conexión", JOptionPane.ERROR_MESSAGE);
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informacionLotePanel = new javax.swing.JPanel();
        identificadorLabel = new javax.swing.JLabel();
        fechaCreacionLabel = new javax.swing.JLabel();
        identificadorTextField = new javax.swing.JTextField();
        identificadorCampoObligatorio = new javax.swing.JLabel();
        fechaCreacionCampoObligatorio = new javax.swing.JLabel();
        referenciaCampoObligatorio = new javax.swing.JLabel();
        fechaCreacionDateChooser = new com.toedter.calendar.JDateChooser();
        cancelarButton = new javax.swing.JButton();
        aceptarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Nuevo Lote");
        setAlwaysOnTop(true);
        setResizable(false);

        informacionLotePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese la información del nuevo lote:"));

        identificadorLabel.setText("Identificador:");

        fechaCreacionLabel.setText("Fecha de Creación:");

        identificadorTextField.setPreferredSize(new java.awt.Dimension(100, 20));

        identificadorCampoObligatorio.setForeground(new java.awt.Color(255, 0, 0));
        identificadorCampoObligatorio.setText("*");

        fechaCreacionCampoObligatorio.setForeground(new java.awt.Color(255, 0, 0));
        fechaCreacionCampoObligatorio.setText("*");

        referenciaCampoObligatorio.setForeground(new java.awt.Color(255, 0, 0));
        referenciaCampoObligatorio.setText("* Campo Obligatorio");

        fechaCreacionDateChooser.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout informacionLotePanelLayout = new javax.swing.GroupLayout(informacionLotePanel);
        informacionLotePanel.setLayout(informacionLotePanelLayout);
        informacionLotePanelLayout.setHorizontalGroup(
            informacionLotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionLotePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacionLotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informacionLotePanelLayout.createSequentialGroup()
                        .addGroup(informacionLotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(identificadorLabel)
                            .addComponent(fechaCreacionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(informacionLotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaCreacionDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(identificadorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(informacionLotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(informacionLotePanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(fechaCreacionCampoObligatorio))
                            .addGroup(informacionLotePanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(identificadorCampoObligatorio))))
                    .addComponent(referenciaCampoObligatorio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        informacionLotePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {fechaCreacionDateChooser, identificadorTextField});

        informacionLotePanelLayout.setVerticalGroup(
            informacionLotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionLotePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacionLotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identificadorLabel)
                    .addComponent(identificadorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identificadorCampoObligatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacionLotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informacionLotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fechaCreacionLabel)
                        .addComponent(fechaCreacionCampoObligatorio))
                    .addComponent(fechaCreacionDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(referenciaCampoObligatorio)
                .addContainerGap())
        );

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(informacionLotePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(aceptarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(informacionLotePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton)
                    .addComponent(aceptarButton))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(275, 203));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        if (!identificadorTextField.getText().equals("")){
            if (fechaCreacionDateChooser.getDate() != null){
                try{
                    String sql = "INSERT INTO lotes( l_identificador, l_fechacreacion, l_estado) VALUES (?, ?, ?);";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, identificadorTextField.getText().toUpperCase());
                    
                    // Preparo fecha
                    java.sql.Date fechaCreacionSql = new java.sql.Date(fechaCreacionDateChooser.getDate().getTime());
                    pst.setDate(2, fechaCreacionSql);
                    
                    pst.setInt(3, 0);//Indica que el lote se esta procesando
                    
                    pst.execute();
                    
                    JOptionPane.showMessageDialog(this, "El nuevo lote fue ingresado exitosamente", "Alta de lote exitosa", JOptionPane.INFORMATION_MESSAGE);
                    
                    this.dispose();
                    
                }catch(SQLException e){
                    // TODO
                    // Luego se deberia cambiar y colocar un mensaje personalizado dependiendo del codigo del error.
                    JOptionPane.showMessageDialog(this, e, "Error al dar de alta nuevo empleado", JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "La fecha de creación del lote no puede ser vacía.", "Error en alta de lote", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "El identificador de lote no puede ser vacío.", "Error en alta de lote", JOptionPane.ERROR_MESSAGE);
        }
           
    }//GEN-LAST:event_aceptarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoLoteScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoLoteScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoLoteScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoLoteScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoLoteScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel fechaCreacionCampoObligatorio;
    private com.toedter.calendar.JDateChooser fechaCreacionDateChooser;
    private javax.swing.JLabel fechaCreacionLabel;
    private javax.swing.JLabel identificadorCampoObligatorio;
    private javax.swing.JLabel identificadorLabel;
    private javax.swing.JTextField identificadorTextField;
    private javax.swing.JPanel informacionLotePanel;
    private javax.swing.JLabel referenciaCampoObligatorio;
    // End of variables declaration//GEN-END:variables
}
