/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class ProveeInsumosScreen extends javax.swing.JFrame {
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form ProveeInsumosScreen
     */
    public ProveeInsumosScreen() {
        initComponents();
        try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", "root");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error en conexión", JOptionPane.ERROR_MESSAGE);
        }
        try{
            String sql = "SELECT p_razonsocial FROM proveedores ORDER BY p_razonsocial";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while (rs.next()){
                String razonSocial = rs.getString("p_razonsocial");
                razonSocialProveedorComboBox.addItem(razonSocial);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error al buscar valores de razón social", JOptionPane.ERROR_MESSAGE);
            
        }
        
        try{
            String sql2 = "SELECT i_descripcion FROM insumos ORDER BY i_descripcion";
            pst = conn.prepareStatement(sql2);
            rs = pst.executeQuery();
            
            while (rs.next()){
                String descripcionInsumo = rs.getString("i_descripcion");
                descripcionInsumoComboBox.addItem(descripcionInsumo);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error al buscar valores de descripción de insumo", JOptionPane.ERROR_MESSAGE);
            
        }
        razonSocialProveedorComboBox.setSelectedIndex(-1);
        descripcionInsumoComboBox.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informacionProvisionPanel = new javax.swing.JPanel();
        razonSocialProveedorLabel = new javax.swing.JLabel();
        descripcionInsumoLabel = new javax.swing.JLabel();
        cantidadProvistaLabel = new javax.swing.JLabel();
        razonSocialProveedorComboBox = new javax.swing.JComboBox();
        descripcionInsumoComboBox = new javax.swing.JComboBox();
        cantidadInsumoProvistaFormattedTextField = new javax.swing.JFormattedTextField();
        cancelarButton = new javax.swing.JButton();
        aceptarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Nueva Provision de Insumo");
        setAlwaysOnTop(true);
        setResizable(false);

        informacionProvisionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese la información de la nueva provisión de insumo:"));

        razonSocialProveedorLabel.setText("Razón Social del Proveedor:");

        descripcionInsumoLabel.setText("Descripción del Insumo:");

        cantidadProvistaLabel.setText("Cantidad de Insumo Provista:");

        cantidadInsumoProvistaFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        cantidadInsumoProvistaFormattedTextField.setPreferredSize(new java.awt.Dimension(275, 20));

        javax.swing.GroupLayout informacionProvisionPanelLayout = new javax.swing.GroupLayout(informacionProvisionPanel);
        informacionProvisionPanel.setLayout(informacionProvisionPanelLayout);
        informacionProvisionPanelLayout.setHorizontalGroup(
            informacionProvisionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionProvisionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacionProvisionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(razonSocialProveedorLabel)
                    .addComponent(descripcionInsumoLabel)
                    .addComponent(cantidadProvistaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacionProvisionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(razonSocialProveedorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descripcionInsumoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadInsumoProvistaFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        informacionProvisionPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cantidadInsumoProvistaFormattedTextField, descripcionInsumoComboBox, razonSocialProveedorComboBox});

        informacionProvisionPanelLayout.setVerticalGroup(
            informacionProvisionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionProvisionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacionProvisionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(razonSocialProveedorLabel)
                    .addComponent(razonSocialProveedorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informacionProvisionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcionInsumoLabel)
                    .addComponent(descripcionInsumoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informacionProvisionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadProvistaLabel)
                    .addComponent(cantidadInsumoProvistaFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(informacionProvisionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(aceptarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(informacionProvisionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton)
                    .addComponent(aceptarButton))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(489, 217));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        PreparedStatement pst2 = null;
        if (razonSocialProveedorComboBox.getSelectedIndex() != -1){
            if (descripcionInsumoComboBox.getSelectedIndex() != -1){
                if (!cantidadInsumoProvistaFormattedTextField.getText().equals("")){
                    try{
                        String sql = "SELECT SM_I_Codigo FROM StocksMensualesInsumos WHERE I_Descripcion_CaracterizadoEn = ? AND SM_I_Fecha = ?";
                        pst = conn.prepareStatement(sql);

                        pst.setString(1, descripcionInsumoComboBox.getSelectedItem().toString());

                        Calendar calendarioActual = Calendar.getInstance();
                        calendarioActual.set(Calendar.DAY_OF_MONTH, 1);

                        java.util.Date today = new java.util.Date(calendarioActual.getTimeInMillis());
                        java.sql.Date fechaActual = new java.sql.Date(today.getTime());

                        pst.setDate(2,fechaActual);

                        rs = pst.executeQuery();
                        
                        if (rs.next()){
                            String sql2 = "INSERT INTO proveeinsumos( p_razonsocial_proveeinsumos, sm_i_codigo_proveeinsumos, cantidadprovista) VALUES (?, ?, ?);";
                            pst2 = conn.prepareStatement(sql2);

                            pst2.setString(1, razonSocialProveedorComboBox.getSelectedItem().toString());
                            pst2.setInt(2, rs.getInt("SM_I_Codigo"));
                            pst2.setFloat(3, ((Number)cantidadInsumoProvistaFormattedTextField.getValue()).floatValue());

                            pst2.execute();
                            
                            JOptionPane.showMessageDialog(this, "Nueva provisión de insumo ingresada satisfactoriamente", "Nueva provisión", JOptionPane.INFORMATION_MESSAGE);
                            
                            this.dispose();
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "NO TIENE QUE OCURRIR", "NO TIENE QUE OCURRIR", JOptionPane.ERROR_MESSAGE);
                        }

                    }catch(Exception e){
                        JOptionPane.showMessageDialog(this, e.getMessage(), "Error al ingresar nueva provisión", JOptionPane.ERROR_MESSAGE);

                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "La cantidad provista no puede ser vacía", "Error al ingresar provisión de insumo", JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Se debe seleccionar un insumo", "Error al ingresar provisión de insumo", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Se debe seleccionar un proveedor", "Error al ingresar provisión de insumo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_aceptarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProveeInsumosScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProveeInsumosScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProveeInsumosScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProveeInsumosScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProveeInsumosScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JFormattedTextField cantidadInsumoProvistaFormattedTextField;
    private javax.swing.JLabel cantidadProvistaLabel;
    private javax.swing.JComboBox descripcionInsumoComboBox;
    private javax.swing.JLabel descripcionInsumoLabel;
    private javax.swing.JPanel informacionProvisionPanel;
    private javax.swing.JComboBox razonSocialProveedorComboBox;
    private javax.swing.JLabel razonSocialProveedorLabel;
    // End of variables declaration//GEN-END:variables
}
